ncbi_taxon_id: "1980442"
ncbi_taxon_name: Orthohantavirus

builds:
  ortho_s:
    segment: s
  ortho_m:
    segment: m
  ortho_l:
    segment: l

ncbi_datasets_fields:
  - accession
  - sourcedb
  - sra-accs
  - isolate-lineage
  - geo-region
  - geo-location
  - isolate-collection-date
  - release-date
  - update-date
  - length
  - host-name
  - isolate-lineage-source
  - biosample-acc
  - submitter-names
  - submitter-affiliation
  - submitter-country

example_metadata: ../data/example/raw_metadata.tsv
example_sequences: ../data/example/raw_sequences.fasta
