builds:
  ortho_s:
    pathogen: Orthohantavirus
    ncbi_taxon_id: "1980442"
    scope: orthohantavirus
    segment: s
    output: hantavirus-nextstrain_S
    priority: 1
    tree_mode: ml
  ortho_m:
    pathogen: Orthohantavirus
    ncbi_taxon_id: "1980442"
    scope: orthohantavirus
    segment: m
    output: hantavirus-nextstrain_M
    priority: 2
    tree_mode: ml
  ortho_l:
    pathogen: Orthohantavirus
    ncbi_taxon_id: "1980442"
    scope: orthohantavirus
    segment: l
    output: hantavirus-nextstrain_L
    priority: 2
    tree_mode: ml

segment_lengths:
  s:
    min: 1200
    max: 2300
  m:
    min: 3200
    max: 4200
  l:
    min: 6000
    max: 7000

required_metadata_columns:
  - accession
  - strain
  - date
  - country
  - division
  - location
  - host
  - segment
  - length
  - authors
  - date_released
  - date_updated
  - segment_assignment_method
  - date_precision
  - qc_status
  - qc_notes
