"""
Phylogenetic workflow for Hantavirus Nextstrain builds.
"""

workdir: workflow.current_basedir

configfile: "defaults/config.yaml"

builds = config["builds"]

wildcard_constraints:
    build="|".join(builds.keys()),

rule all:
    input:
        expand("auspice/{build}.json", build=builds.keys()),

include: "rules/prepare_inputs.smk"
include: "rules/build_tree.smk"
include: "rules/export.smk"
