builds:
  ortho_s:
    segment: s
    input_metadata: ../ingest/results/ortho_s/metadata.tsv
    input_sequences: ../ingest/results/ortho_s/sequences.fasta
    output: ortho_s
    min_length: 1500
    tree_mode: ml
  ortho_m:
    segment: m
    input_metadata: ../ingest/results/ortho_m/metadata.tsv
    input_sequences: ../ingest/results/ortho_m/sequences.fasta
    output: ortho_m
    min_length: 3000
    tree_mode: ml
  ortho_l:
    segment: l
    input_metadata: ../ingest/results/ortho_l/metadata.tsv
    input_sequences: ../ingest/results/ortho_l/sequences.fasta
    output: ortho_l
    min_length: 5500
    tree_mode: ml
  ortho_s_time:
    segment: s
    input_metadata: ../ingest/results/ortho_s/metadata.tsv
    input_sequences: ../ingest/results/ortho_s/sequences.fasta
    output: ortho_s_time
    min_length: 1500
    tree_mode: timetree
    date_precisions:
      - day
      - month
      - year
    min_year: 2010
    clock_filter_iqd: 4
  ortho_m_time:
    segment: m
    input_metadata: ../ingest/results/ortho_m/metadata.tsv
    input_sequences: ../ingest/results/ortho_m/sequences.fasta
    output: ortho_m_time
    min_length: 3000
    tree_mode: timetree
    date_precisions:
      - day
      - month
      - year
    min_year: 2010
    clock_filter_iqd: 4
  ortho_l_time:
    segment: l
    input_metadata: ../ingest/results/ortho_l/metadata.tsv
    input_sequences: ../ingest/results/ortho_l/sequences.fasta
    output: ortho_l_time
    min_length: 5500
    tree_mode: timetree
    date_precisions:
      - day
      - month
      - year
    min_year: 2010
    clock_filter_iqd: 4

strain_id_field: accession
traits:
  columns:
    - country
    - host

export:
  auspice_config: defaults/auspice_config.json
  description: defaults/description.md
